<a href="https://colab.research.google.com/github/himanshugithub360/PyTroch/blob/main/Tensor_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
print(torch.__version__)

2.11.0+cu128


In [5]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [10]:
# using empty
a = torch.empty(2,3)

In [11]:
type(a)

torch.Tensor

In [15]:
# using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
#Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
# Using rand
torch.rand(2,3)

tensor([[0.6385, 0.7225, 0.4647],
        [0.8698, 0.5545, 0.1063]])

In [20]:
# use of seed
torch.manual_seed(122)
torch.rand(2,3)

tensor([[0.1899, 0.8691, 0.7658],
        [0.4226, 0.9384, 0.1215]])

In [26]:
# using tensor
torch.tensor([[1,2,3],[5,6,7]])

tensor([[1, 2, 3],
        [5, 6, 7]])

In [33]:
# other ways

# arrange
print("using arrange -> ", torch.arange(0,10,2))

# using linspace
print("using linspace -> ", torch.linspace(0,10,5))

# using eye
print("using eye , it print identity matrix ->", torch.eye(5))

# using full
print("using full -> ", torch.full((3,3),5))


using arrange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye , it print identity matrix -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [35]:
X = torch.tensor([[1,2,3],[4,5,6]])
X


tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
X.shape

torch.Size([2, 3])

In [41]:
torch.empty_like(X)

tensor([[133710258236832, 133710258236832,      1083871968],
        [     1087616432,               0,      1053765648]])

In [42]:
torch.zeros_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [43]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [48]:
torch.rand_like(X)
# it gives error because X is of int type and rand generate float data type

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [50]:
torch.rand_like(X, dtype=torch.float64)

tensor([[0.1491, 0.3142, 0.6073],
        [0.8966, 0.2346, 0.3883]], dtype=torch.float64)

# Tensor Data Types

In [51]:
# find data types
X.dtype

torch.int64

In [61]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [65]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [66]:
# using to()
X.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations

## 1. Scalar Operations

In [3]:
x = torch.rand(2,2)
x

tensor([[0.0056, 0.2353],
        [0.4484, 0.8340]])

In [15]:
# addition
x + 2

# subtraction
x -2

# multiplication
x * 3

# division
x / 3

# mod
((x * 100)//3)%2

# power
x**2


tensor([[3.1278e-05, 5.5355e-02],
        [2.0111e-01, 6.9552e-01]])

## 2. Element wise operation

In [16]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print (a)
print(b)

tensor([[0.6593, 0.4622, 0.9779],
        [0.7712, 0.6124, 0.3755]])
tensor([[0.8141, 0.4209, 0.9511],
        [0.7955, 0.2035, 0.1727]])


In [19]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.6593, 0.0413, 0.0268],
        [0.7712, 0.0019, 0.0300]])

In [20]:
c = torch.tensor([1 ,-3,3,4,-5])

In [21]:
# abs
torch.abs(c)


tensor([1, 3, 3, 4, 5])

In [22]:
# negative
torch.neg(c)

tensor([-1,  3, -3, -4,  5])

In [23]:
d = torch.tensor([1.9, 2.3, 3.5, 8.9])

In [24]:
# round
torch.round(d)

tensor([2., 2., 4., 9.])

In [25]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 9.])

In [26]:
# floor
torch.floor(d)

tensor([1., 2., 3., 8.])

In [27]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction operation

In [28]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[5., 2., 4.],
        [7., 0., 5.]])

In [31]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim = 0)

# sum along rows
torch.sum(e, dim = 1)

tensor([11., 12.])

In [34]:
# mean
torch.mean(e)

# mean along column
torch.mean(e , dim = 0)

# mean along rows
torch.mean(e , dim = 1)

tensor([3.6667, 4.0000])

In [35]:
# median
torch.median(e)

tensor(4.)

In [36]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [37]:
# product
torch.prod(e)

tensor(0.)

In [38]:
# standard deviation
torch.std(e)

tensor(2.4833)

In [39]:
# variance
torch.var(e)

tensor(6.1667)

In [40]:
# argmax -> index of max value
torch.argmax(e)

tensor(3)

In [42]:
# argmin -> index of min value
torch.argmin(e)

tensor(4)

## 4. Matrix operation

In [4]:
f = torch.randint(size = (2,3), low = 0, high = 10)
g = torch.randint(size = (3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[9, 8, 2],
        [7, 0, 5]])
tensor([[5, 3],
        [9, 9],
        [9, 6]])


In [5]:
# matrix multiplication
torch.matmul(f,g)

tensor([[135, 111],
        [ 80,  51]])

In [6]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

# dot Product
torch.dot(vector1, vector2)

tensor(32)

In [7]:
torch.transpose(f,0,1)

tensor([[9, 7],
        [8, 0],
        [2, 5]])

In [10]:
h = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float32)
h

tensor([[4., 0., 0.],
        [9., 3., 0.],
        [9., 1., 9.]])

In [11]:
# Determinat
torch.det(h)

tensor(108.)

In [12]:
# Inverse
torch.inverse(h)

tensor([[ 2.5000e-01,  6.6227e-09, -1.2418e-09],
        [-7.5000e-01,  3.3333e-01,  3.7253e-09],
        [-1.6667e-01, -3.7037e-02,  1.1111e-01]])

## 5. Comparison operations

In [13]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 2, 9],
        [5, 4, 1]])
tensor([[5, 0, 1],
        [4, 0, 6]])


In [15]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

## 6. Special Functions

In [16]:
k = torch.randint(size = (2, 3), low = 0, high = 10, dtype = torch.float32)

In [17]:
k

tensor([[4., 2., 4.],
        [0., 1., 1.]])

In [18]:
# log
torch.log(k)

tensor([[1.3863, 0.6931, 1.3863],
        [  -inf, 0.0000, 0.0000]])

In [19]:
# exp
torch.exp(k)

tensor([[54.5981,  7.3891, 54.5981],
        [ 1.0000,  2.7183,  2.7183]])

In [20]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 1.4142, 2.0000],
        [0.0000, 1.0000, 1.0000]])

In [21]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.8808, 0.9820],
        [0.5000, 0.7311, 0.7311]])

In [29]:
# softmax
torch.softmax(k, dim = 0)

tensor([[0.9820, 0.7311, 0.9526],
        [0.0180, 0.2689, 0.0474]])

In [30]:
# relu
torch.relu(k)

tensor([[4., 2., 4.],
        [0., 1., 1.]])

# Inplace Operation

In [31]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9969, 0.6785, 0.7043],
        [0.4911, 0.9522, 0.2388]])
tensor([[0.3457, 0.9925, 0.8248],
        [0.7953, 0.1270, 0.5295]])


In [35]:
k = m + n

In [40]:
l = m.add_(n)

In [41]:
id(m)

135781313246496

In [42]:
id(l)

135781313246496

In [43]:
id(n)

135781313490576

In [44]:
m.relu_()

tensor([[1.3426, 1.6710, 1.5290],
        [1.2864, 1.0792, 0.7683]])

# Copying a Tenosr

In [45]:
a = torch.rand(2,3)
a

tensor([[0.5623, 0.9260, 0.7304],
        [0.1928, 0.1846, 0.8558]])

In [49]:
b = a
# both are referencing to the same address , any changes in one element shows in other also


In [50]:
id(a)

135781314975280

In [51]:
id(b)

135781314975280

In [52]:
a[0][0] = 0

In [53]:
print(a)
print(b)

tensor([[0.0000, 0.9260, 0.7304],
        [0.1928, 0.1846, 0.8558]])
tensor([[0.0000, 0.9260, 0.7304],
        [0.1928, 0.1846, 0.8558]])


In [54]:
# For Copying the element , use clone
b = a.clone()

In [55]:
a[0][0] = 98

In [56]:
a

tensor([[98.0000,  0.9260,  0.7304],
        [ 0.1928,  0.1846,  0.8558]])

In [57]:
b

tensor([[0.0000, 0.9260, 0.7304],
        [0.1928, 0.1846, 0.8558]])

In [58]:
id(a)

135781314975280

In [59]:
id(b)

135784529123344

# Tensor Operation on GPU

In [61]:
torch.cuda.is_available()

True

In [62]:
device = torch.device('cuda')

In [63]:
# Creating a new tensor on GPU
torch.rand((2,3), device = device)

tensor([[0.7448, 0.4003, 0.2185],
        [0.7713, 0.4789, 0.5226]], device='cuda:0')

In [64]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.7443, 0.4554, 0.6040],
        [0.9873, 0.0796, 0.3503]])

In [67]:
b = a.to(device)

In [68]:
b + 5

tensor([[5.7443, 5.4554, 5.6040],
        [5.9873, 5.0796, 5.3503]], device='cuda:0')

# Checking a Runtime of CPU and GPU

In [5]:
import time
import torch
size = 10000
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU : {cpu_time:.4f} seconds")

Matrix_gpu1 = matrix_cpu1.to('cuda')
Matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(Matrix_gpu1, Matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time


print(f"Time on GPU : {gpu_time:.4f} seconds")

Time on CPU : 17.1820 seconds
Time on GPU : 0.5752 seconds


# Conversion of numpy and tensor

In [5]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [6]:
b = a.numpy()

In [7]:
b

array([1, 2, 3])

In [8]:
type(b)

numpy.ndarray

In [9]:
import numpy as np
c = np.array([1,2,3])

In [10]:
torch.from_numpy(c)

tensor([1, 2, 3])